[package]
name = "kisaragi-booth-utility"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.0.32", features = ["derive"] }
reqwest = { version = "0.11.13", features = ["json", "gzip", "deflate", "multipart"] }
select = "0.6.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sqlite3 = "0.24.0"
strum = { version = "0.24.1", features = ["derive"] }
tempfile = "3.3.0"
thiserror = "1.0.38"
tokio = { version = "1.24.1", features = ["rt", "rt-multi-thread", "macros"] }
